### ISSUE TITLE
Hide slider buttons and disable swiping

### ISSUE THREAD

**Issue by luccascorrea** [banthagroup/fslightbox#132]
Hi!

For a specific use case, I would like users to not be able to swipe to change the slide. Also I'd like to hide the previous/next buttons (I added links to the page that will open a specific slide and I'd like the user to navigate using those).

Is this possible?

Thanks!

**Comment by piotrzdziarski** [comment]
You can do it via CSS:
```css
.fslightbox-slide-btn-container {
  display: none !important;
}

.fslightbox-container > .fslightbox-absoluted {
  pointer-events: none;
}
```
But this solution works only for images, because it disables video and youtube controls.
