### ISSUE TITLE
Not compatible with CSS Containers

### ISSUE THREAD

**Issue by MattWilcox** [banthagroup/fslightbox#218]
CSS Containers create a new stacking context; if any element wrapping an FSLightbox has a CSS Container set on it, the layout for the lightbox breaks and no content or navigation is visible.

e.g.,

```html
<body>
  <main>
    lightbox stuff
  </main>
</body>
```

```css
main {
  container: mainElement / inline-size;
}
```

Now it's all broken.
